import { Product, Slot, Booking } from '../types';

// Genuine Official Ayyan Fireworks 2024–2026 Price List & Inventory Master
export const INITIAL_PRODUCTS: Product[] = [
  // =========================================================================
  // 1. MAROONS & SOUND CRACKERS
  // =========================================================================
  {
    id: 'ayyan-0801',
    code: '0801',
    name: 'Ganesh Crackers',
    category: 'Maroons',
    price: 3605,
    piece_count: '100 Pkts',
    description: 'Authentic Sivakasi traditional red sound maroons with crisp gunpowder report and thunderous echo.',
    safety_instructions: 'Place flat on open ground. Ignite fuse using an agarbatti and retreat immediately to 10 meters distance.',
    safety_tags: ['High Decibel', 'Festive Salute', 'PESO Certified', 'Bunny Brand'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0803',
    code: '0803',
    name: 'Lakshmi Crackers',
    category: 'Maroons',
    price: 2070,
    piece_count: '100 Pkts',
    description: 'Classic single-burst festive crackers with loud, sharp report celebrating auspicious beginnings.',
    safety_instructions: 'Light individually in clear open space. Do not ignite inside containers or bottles.',
    safety_tags: ['Auspicious Burst', 'Traditional Formula', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0802',
    code: '0802',
    name: 'Bengal Prince Crackers',
    category: 'Maroons',
    price: 3605,
    piece_count: '100 Pkts',
    description: 'Royal-grade sound crackers with supreme decibel clarity and clean detonation report.',
    safety_instructions: 'Keep spectators at minimum 10m clearance. Light from side with cotton garments.',
    safety_tags: ['Royal Grade', 'Crisp Report', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0804',
    code: '0804',
    name: 'King Crackers',
    category: 'Maroons',
    price: 2070,
    piece_count: '100 Pkts',
    description: 'High-decibel celebration crackers specially blended for Diwali processions and grand gatherings.',
    safety_instructions: 'Outdoor open ground ignition only. Never bend over cracker during lighting.',
    safety_tags: ['Heavy Report', 'Procession Grade', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0805',
    code: '0805',
    name: 'Jawan Crackers',
    category: 'Maroons',
    price: 1615,
    piece_count: '100 Pkts',
    description: 'Medium-range family crackers with reliable fast ignition and lively crackling report.',
    safety_instructions: 'Lay flat on dry concrete or earth. Light and step back 5 meters.',
    safety_tags: ['Family Celebration', 'Quick Burst', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0806',
    code: '0806',
    name: 'Bird Crackers',
    category: 'Maroons',
    price: 835,
    piece_count: '100 Pkts',
    description: 'Compact quick-burst family celebration crackers with sharp crackling sound.',
    safety_instructions: 'Place on ground, light with agarbatti and move to a safe distance.',
    safety_tags: ['Compact Pkts', 'Lively Crackle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 2. SPARKLERS
  // =========================================================================
  {
    id: 'ayyan-0101',
    code: '0101',
    name: '7 cm Electric Sparklers',
    category: 'Sparklers',
    price: 1175,
    piece_count: '100 Boxes',
    description: 'Pure silver glitter sparklers with smokeless green chemistry formula. Child-safe family favorite.',
    safety_instructions: 'Hold by wire at arms length pointing away from body. Immerse spent wire into bucket of water.',
    safety_tags: ['Smokeless', 'Child Safe', 'Green Chemistry', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0102',
    code: '0102',
    name: '7 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 1325,
    piece_count: '100 Boxes',
    description: 'Vibrant multi-colored sparkling handheld sticks with ruby, emerald, and golden stars.',
    safety_instructions: 'Wear cotton clothing. Light one at a time and extinguish spent sticks in water.',
    safety_tags: ['Multi-Colour', 'Vivid Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0103',
    code: '0103',
    name: '9 cm Electric Sparklers',
    category: 'Sparklers',
    price: 1325,
    piece_count: '100 Boxes',
    description: 'Extended duration gold and silver sparkling star discharge with uniform bright burn.',
    safety_instructions: 'Hold at arm length. Do not touch glowing wire tip.',
    safety_tags: ['Uniform Burn', 'Bright Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0104',
    code: '0104',
    name: '9 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 1500,
    piece_count: '100 Boxes',
    description: 'Rich emerald, ruby, and golden star bursts designed for family festive moments.',
    safety_instructions: 'Keep water bucket nearby. Never wave near clothing or hair.',
    safety_tags: ['Vibrant Hues', 'Low Smoke', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0105',
    code: '0105',
    name: '10 cm Ruby Sparklers',
    category: 'Sparklers',
    price: 210,
    piece_count: '10 Boxes',
    description: 'Deep ruby crimson sparkling glow with intense luminosity and minimal smoke.',
    safety_instructions: 'Hold firmly by wire base. Dip in water after use.',
    safety_tags: ['Ruby Red', 'High Luminosity', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0109',
    code: '0109',
    name: '12 cm Electric Sparklers',
    category: 'Sparklers',
    price: 180,
    piece_count: '10 Boxes',
    description: 'Brilliant white electric sparklers with steady, continuous sparkling cascade.',
    safety_instructions: 'Outdoor use recommended. Light with agarbatti or candle.',
    safety_tags: ['Bright White', 'Steady Burn', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0110',
    code: '0110',
    name: '12 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 240,
    piece_count: '10 Boxes',
    description: '4-color shifting dazzling handheld fireworks with emerald, sapphire, and gold sparks.',
    safety_instructions: 'Hold at arm length. Extinguish spent rods in water.',
    safety_tags: ['4-Color Shift', 'Extended Flame', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0111',
    code: '0111',
    name: '15 cm Electric Sparklers',
    category: 'Sparklers',
    price: 400,
    piece_count: '10 Boxes',
    description: 'Long glitter sticks ideal for weddings, temple entrances, and grand Diwali evening displays.',
    safety_instructions: 'Maintain 2 meters distance from others. Do not touch hot wire.',
    safety_tags: ['Grand Entrance', 'Long Burn', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0112',
    code: '0112',
    name: '15 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 530,
    piece_count: '10 Boxes',
    description: 'Heavy multi-color sparkle discharge with long burning time and brilliant flare.',
    safety_instructions: 'Extinguish wire in water bucket immediately after burn ends.',
    safety_tags: ['Heavy Discharge', 'Multi-Color', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0115',
    code: '0115',
    name: '15 cm Panchavarnam 5 In 1',
    category: 'Sparklers',
    price: 460,
    piece_count: '10 Boxes',
    description: '5 distinct sequential color transformations in a single sparkle stick: red, gold, green, blue, and silver.',
    safety_instructions: 'Hold at arm length pointing away from body. Keep in sight until spent.',
    safety_tags: ['Panchavarnam', '5-Color Shift', 'Iconic Ayyan', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0116',
    code: '0116',
    name: '30 cm Electric Sparklers',
    category: 'Sparklers',
    price: 400,
    piece_count: '10 Boxes',
    description: 'Extra-long mega burning family sparkler sticks with dense golden sparks for over 90 seconds.',
    safety_instructions: 'Adult supervision required. Always discard wire in water bucket.',
    safety_tags: ['30cm Mega', '90s Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0117',
    code: '0117',
    name: '30 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 530,
    piece_count: '10 Boxes',
    description: '30cm giant colored sparklers showering deep ruby and emerald stars in wide radii.',
    safety_instructions: 'Keep 2m clearance. Do not inhale smoke directly.',
    safety_tags: ['30cm Colored', 'Vivid Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0118',
    code: '0118',
    name: '50 cm Electric Sparklers',
    category: 'Sparklers',
    price: 1020,
    piece_count: '10 Boxes',
    description: 'Giant 50cm sparklers with over 3 minutes of continuous burn and towering sparkling canopy.',
    safety_instructions: 'Hold with two hands if needed. Place spent rod into water immediately.',
    safety_tags: ['50cm Giant', '3 Min Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0119',
    code: '0119',
    name: '50 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 1260,
    piece_count: '10 Boxes',
    description: 'Mega colored sparkling sticks for extended celebrations and photography moments.',
    safety_instructions: 'Use outdoors only with safe clearance from trees and inflammable materials.',
    safety_tags: ['50cm Colored', 'Photo-Grade', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0120',
    code: '0120',
    name: '75 cm Electric Sparklers',
    category: 'Sparklers',
    price: 1700,
    piece_count: '10 Boxes',
    description: 'Colossal 75cm luxury sparkler sticks with maximum pyrotechnic star discharge.',
    safety_instructions: 'Ensure full clearance of 3 meters. Hold at waist height pointing upwards.',
    safety_tags: ['75cm Colossal', 'Grand Finale', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0123',
    code: '0123',
    name: 'Rajadhani Sparklers (5 Varieties)',
    category: 'Sparklers',
    price: 238,
    piece_count: 'Box',
    description: 'Assorted gift collection of 5 premium varieties of sparklers in a single showcase box.',
    safety_instructions: 'Follow box guidelines for each variety. Extinguish in water.',
    safety_tags: ['5 Varieties Assorted', 'Gift Presentation', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 3. CHAKKARS & WHEELS
  // =========================================================================
  {
    id: 'ayyan-0201',
    code: '0201',
    name: 'Ground Chakkar Medium',
    category: 'Chakkars',
    price: 248,
    piece_count: '4 Boxes',
    description: 'High-speed golden rotating spinner wheel creating concentric sparkling rings on smooth ground.',
    safety_instructions: 'Place flat on level concrete ground. Light fuse and step back 5 meters.',
    safety_tags: ['Concentric Rings', 'Fast Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0202',
    code: '0202',
    name: 'Ground Chakkar Big',
    category: 'Chakkars',
    price: 350,
    piece_count: '4 Boxes',
    description: 'Wide-radius silver spinner with rapid rotational velocity and bright halo effect.',
    safety_instructions: 'Ensure clear flat floor free of debris. Maintain 5m safe perimeter.',
    safety_tags: ['Wide Radius', 'Bright Halo', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0203',
    code: '0203',
    name: 'Ground Chakkar Special',
    category: 'Chakkars',
    price: 820,
    piece_count: '10 Boxes',
    description: 'Special long-running sparkling ground spinner with dual gold and red corona.',
    safety_instructions: 'Place flat, light fuse, and step back immediately.',
    safety_tags: ['Dual Corona', 'Long Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0204',
    code: '0204',
    name: 'Ground Chakkar Deluxe',
    category: 'Chakkars',
    price: 1450,
    piece_count: '10 Boxes',
    description: 'Deluxe dual-color rotational fireworks wheel with heavy gold star dispersion.',
    safety_instructions: 'Smooth hard surface required. Never touch while spinning.',
    safety_tags: ['Deluxe Grade', 'Heavy Dispersion', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0205',
    code: '0205',
    name: 'Krishna Chakkar Big',
    category: 'Chakkars',
    price: 440,
    piece_count: '4 Boxes',
    description: 'Legendary Bunny Brand Krishna design with brilliant sparkling aura and steady spin.',
    safety_instructions: 'Place horizontally on flat floor. Light from side.',
    safety_tags: ['Krishna Brand', 'Iconic Classic', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0206',
    code: '0206',
    name: 'Krishna Chakkar Special',
    category: 'Chakkars',
    price: 860,
    piece_count: '10 Boxes',
    description: 'Extended duration Krishna spinner producing multi-tiered fiery circles.',
    safety_instructions: 'Ensure clear ground away from dry vegetation.',
    safety_tags: ['Multi-Tiered', 'Extended Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0208',
    code: '0208',
    name: 'Giant Wheel',
    category: 'Wheels',
    price: 103,
    piece_count: 'Box',
    description: 'Dynamic rotating wheel fireworks with dual-color aura and spinning crackles.',
    safety_instructions: 'Mount securely on nail/rod as per packaging instructions before lighting.',
    safety_tags: ['Giant Wheel', 'Mounted Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0209',
    code: '0209',
    name: 'Joke Wheel',
    category: 'Wheels',
    price: 103,
    piece_count: 'Box',
    description: 'Whimsical spinning wheel with surprise crackling finish and lively color transitions.',
    safety_instructions: 'Secure to wooden post with supplied nail. Light and step back 5 meters.',
    safety_tags: ['Crackling Finish', 'Novelty Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0210',
    code: '0210',
    name: 'Star Wheel',
    category: 'Wheels',
    price: 88,
    piece_count: 'Box',
    description: 'Brilliant star-shaped spinning ground wheel emitting high-velocity gold sparks.',
    safety_instructions: 'Place flat on open ground or mount on pole. Light fuse and retreat.',
    safety_tags: ['Star Shaped', 'High Velocity', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0211',
    code: '0211',
    name: 'Classic Wheel',
    category: 'Wheels',
    price: 174,
    piece_count: 'Box',
    description: 'High rotational speed classic wheel with radiant gold aura.',
    safety_instructions: 'Mount on vertical post before lighting.',
    safety_tags: ['Classic Wheel', 'Gold Aura', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0212',
    code: '0212',
    name: 'Whistling Wheel',
    category: 'Wheels',
    price: 112,
    piece_count: 'Box',
    description: 'Auditory spinning wheel producing a pleasant musical whistle accompanied by golden sparks.',
    safety_instructions: 'Mount firmly on nail, light and maintain 5 meters distance.',
    safety_tags: ['Whistling Tone', 'Audio Spectacle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0215',
    code: '0215',
    name: 'Glittering Wheel',
    category: 'Wheels',
    price: 100,
    piece_count: 'Box',
    description: 'Multi-color glittering rotation effect with sparkling silver strobe bursts.',
    safety_instructions: 'Mount securely on post. Keep clear of overhead obstacles.',
    safety_tags: ['Glittering Strobe', 'Silver Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0221',
    code: '0221',
    name: 'Lotus Wheel',
    category: 'Wheels',
    price: 70,
    piece_count: 'Box',
    description: 'Petal-shaped floral fountain spinner mimicking a blooming lotus flower on the ground.',
    safety_instructions: 'Place flat on open ground. Light and step back.',
    safety_tags: ['Blooming Lotus', 'Floral Spinner', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 4. FOUNTAINS & COLOUR FOUNTAINS (FLOWER POTS)
  // =========================================================================
  {
    id: 'ayyan-0301',
    code: '0301',
    name: 'Flower Pots Small',
    category: 'Flower Pots',
    price: 500,
    piece_count: '10 Boxes',
    description: 'Golden shower fountain shooting 8 feet high with classic bell-shaped canopy.',
    safety_instructions: 'Place pot upright on level ground. Do not lean over pot during lighting.',
    safety_tags: ['Golden Shower', 'Family Favorite', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1533230307785-f01f01639d67?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0302',
    code: '0302',
    name: 'Flower Pots Big',
    category: 'Flower Pots',
    price: 800,
    piece_count: '10 Boxes',
    description: 'Volcanic gold and silver sparkling shower with wide canopy shooting 12 feet high.',
    safety_instructions: 'Stand upright on level concrete or ground. Light and step back 5 meters.',
    safety_tags: ['Volcanic Shower', '12ft Fountain', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0303',
    code: '0303',
    name: 'Flower Pots Special',
    category: 'Flower Pots',
    price: 1250,
    piece_count: '10 Boxes',
    description: 'Extra high sparkling canopy cone fountain with dense titanium sparks spray.',
    safety_instructions: 'Outdoor open sky only. Keep clear of overhead wires.',
    safety_tags: ['Extra High Canopy', 'Titanium Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0304',
    code: '0304',
    name: 'Flower Pots Giant',
    category: 'Flower Pots',
    price: 265,
    piece_count: 'Box',
    description: 'Towering 15-foot sparkling fountain spray with brilliant crackling finish.',
    safety_instructions: 'Ensure vertical placement on firm soil or patio. Step back 6 meters.',
    safety_tags: ['15ft Giant', 'Crackling Finish', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0307',
    code: '0307',
    name: 'Flower Pots Red',
    category: 'Flower Pots',
    price: 1430,
    piece_count: '10 Boxes',
    description: 'Deep ruby red sparkling shower transforming into golden cascading rain.',
    safety_instructions: 'Place upright. Light fuse and retreat.',
    safety_tags: ['Ruby Red Shower', 'Golden Rain', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0309',
    code: '0309',
    name: 'Tri Colour Fountain',
    category: 'Flower Pots',
    price: 215,
    piece_count: 'Box',
    description: 'Three distinct sequential color bursts representing saffron, white, and emerald green.',
    safety_instructions: 'Place on ground, light and maintain 5m safe distance.',
    safety_tags: ['Tri-Colour', 'Patriotic Sparkle', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0310',
    code: '0310',
    name: 'Rangoli',
    category: 'Flower Pots',
    price: 136,
    piece_count: 'Box',
    description: 'Floral pattern sparkling stage fountain illuminating intricate festive color designs.',
    safety_instructions: 'Outdoor use only. Place upright on flat floor.',
    safety_tags: ['Floral Pattern', 'Rangoli Hues', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0311',
    code: '0311',
    name: 'Jadugar',
    category: 'Colourful Fountains',
    price: 155,
    piece_count: 'Box',
    description: 'Multi-color morphing stage fountain with ruby-to-emerald transitions and strobe effects.',
    safety_instructions: 'Keep clear of overhead obstacles. Light with long agarbatti.',
    safety_tags: ['Morphing Colors', 'Stage Fountain', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0312',
    code: '0312',
    name: 'Manoranjan',
    category: 'Colourful Fountains',
    price: 155,
    piece_count: 'Box',
    description: 'Vibrant family celebration stage fountain with sparkling multi-hue floral fountains.',
    safety_instructions: 'Place upright. Light and maintain 5 meters clearance.',
    safety_tags: ['Multi-Hue', 'Family Delight', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0313',
    code: '0313',
    name: 'Roopkhela',
    category: 'Colourful Fountains',
    price: 270,
    piece_count: 'Box',
    description: 'Multi-shade sparkling fountain with luminous color changes and gentle whistling aura.',
    safety_instructions: 'Place on firm, flat ground. Light fuse and step back.',
    safety_tags: ['Luminous Shades', 'Gentle Whistle', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0314',
    code: '0314',
    name: 'Varnajal',
    category: 'Colourful Fountains',
    price: 242,
    piece_count: 'Box',
    description: 'Vibrant shower cascade of emerald, violet, and gold stars rising 10 feet into the night.',
    safety_instructions: 'Outdoor use only. Do not tilt while lighting.',
    safety_tags: ['Vibrant Cascade', '10ft Rise', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0322',
    code: '0322',
    name: 'Fire Drops',
    category: 'Colourful Fountains',
    price: 74,
    piece_count: 'Box',
    description: 'Cascading golden rain drops with red strobe accents and shimmering ground carpet.',
    safety_instructions: 'Place upright on flat surface, ignite fuse and step back.',
    safety_tags: ['Golden Rain', 'Red Strobe', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0323',
    code: '0323',
    name: 'Snow Patrol',
    category: 'Colourful Fountains',
    price: 74,
    piece_count: 'Box',
    description: 'Silver white sparkling shower effect mimicking falling snow crystals under moonlight.',
    safety_instructions: 'Place on level patio or ground. Light and step back.',
    safety_tags: ['Silver Snow', 'Moonlight Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0325',
    code: '0325',
    name: 'Colour Koti Deluxe',
    category: 'Flower Pots',
    price: 368,
    piece_count: 'Box',
    description: 'High power mega canopy fountain with dense gold and ruby showers.',
    safety_instructions: 'Keep clear of overhead obstructions. Light and retreat.',
    safety_tags: ['Mega Canopy', 'Deluxe Koti', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0336',
    code: '0336',
    name: 'Mega Peacock',
    category: 'Colourful Fountains',
    price: 288,
    piece_count: 'Box',
    description: 'Broad multi-nozzle fan fountain mimicking majestic peacock feathers with turquoise & gold spray.',
    safety_instructions: 'Position on flat open ground facing spectators. Maintain 6m clearance.',
    safety_tags: ['Peacock Feather Fan', 'Multi-Nozzle', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 5. ROCKETS & NOVELTIES
  // =========================================================================
  {
    id: 'ayyan-1202',
    code: '1202',
    name: 'Colour Rocket',
    category: 'Sky Rockets',
    price: 650,
    piece_count: '10 Boxes',
    description: 'High-altitude vertical ascent with starry color canopy and trailing sparks.',
    safety_instructions: 'Place stick inside an upright bottle or launch tube. Never hold by hand.',
    safety_tags: ['Vertical Ascent', 'Color Canopy', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1203',
    code: '1203',
    name: 'Rocket Bomb',
    category: 'Sky Rockets',
    price: 794,
    piece_count: '10 Boxes',
    description: 'Fast whistling ascent ending in heavy aerial salute report high in the night sky.',
    safety_instructions: 'Insert launch guide into empty bottle. Ensure straight vertical launch angle.',
    safety_tags: ['Whistling Ascent', 'Aerial Salute', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1204',
    code: '1204',
    name: 'Flower Missile',
    category: 'Sky Rockets',
    price: 750,
    piece_count: '10 Boxes',
    description: 'Rocket with sparkling floral spray trailing the sky before bursting into starry peony bouquet.',
    safety_instructions: 'Launch vertically outdoors with 15 meters clear perimeter.',
    safety_tags: ['Floral Spray', 'Peony Bouquet', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1205',
    code: '1205',
    name: 'Sound Missile',
    category: 'Sky Rockets',
    price: 930,
    piece_count: '10 Boxes',
    description: 'High altitude screaming sound missile with double report aerial burst.',
    safety_instructions: 'Use stable vertical launch bottle. Light and retreat immediately.',
    safety_tags: ['Double Report', 'High Screamer', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1210',
    code: '1210',
    name: 'Parachute Rocket',
    category: 'Sky Rockets',
    price: 215,
    piece_count: 'Box',
    description: 'Ascends 100+ meters and slowly descends with a glowing color flare on a miniature parachute.',
    safety_instructions: 'Ensure wide open sky free from rooftops or overhead wires.',
    safety_tags: ['Parachute Flare', 'Slow Descent', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1213',
    code: '1213',
    name: 'Air Whistle',
    category: 'Sky Rockets',
    price: 145,
    piece_count: 'Box',
    description: 'Auditory whistling sky rocket ascending with musical siren effect.',
    safety_instructions: 'Launch vertically from open ground with launch bottle.',
    safety_tags: ['Musical Siren', 'Sky Whistle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1300',
    code: '1300',
    name: 'Pop Pop Crackling',
    category: 'Novelties',
    price: 27,
    piece_count: 'Box',
    description: 'Friction-sensitive drop snaps producing safe, fun pop sounds for kids.',
    safety_instructions: 'Throw against hard surface. Do not put in mouth or pockets.',
    safety_tags: ['Drop Snap', 'Child Fun', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-8570',
    code: '8570',
    name: 'Super Drone',
    category: 'Novelties',
    price: 72,
    piece_count: 'Box',
    description: 'Spinning saucer novelty that lifts off vertically like a glowing mini helicopter into the night sky.',
    safety_instructions: 'Place flat on open ground with wings horizontal. Light and step back 5 meters.',
    safety_tags: ['Vertical Lift-Off', 'Spinning Saucer', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 6. CAKES / AERIAL MULTI-SHOTS
  // =========================================================================
  {
    id: 'ayyan-1701',
    code: '1701',
    name: 'Dekhe Man - 12 Star',
    category: 'Aerial Multi-Shots',
    price: 120,
    piece_count: 'Box',
    description: 'Sequential 12-star multi-color night sky barrage firing vivid glittering pearls into the atmosphere.',
    safety_instructions: 'Place box upright on flat hard ground. Wedge with bricks so it cannot tip over.',
    safety_tags: ['12 Stars', 'Multi-Color Barrage', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1770',
    code: '1770',
    name: 'Daisy Bees - 12 Star Yellow',
    category: 'Aerial Multi-Shots',
    price: 127,
    piece_count: 'Box',
    description: 'Dancing yellow comet stars with crackling audio reports soaring into aerial formations.',
    safety_instructions: 'Secure box firmly with bricks on open ground before lighting fuse.',
    safety_tags: ['Dancing Comets', 'Yellow Stars', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1705',
    code: '1705',
    name: 'Sky Storm - 12 Shot',
    category: 'Aerial Multi-Shots',
    price: 128,
    piece_count: 'Box',
    description: 'Thunderous aerial breaks with palm tree brocade effects and silver strobe bursts.',
    safety_instructions: 'Outdoor open sky only. Never lean over cake while lighting.',
    safety_tags: ['Palm Tree Brocade', 'Silver Strobe', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1702',
    code: '1702',
    name: 'Chal Mere Sath - 25 Shot',
    category: 'Aerial Multi-Shots',
    price: 238,
    piece_count: 'Box',
    description: '25-shot rapid-fire canopy filled with golden willow stars and crimson peony breaks.',
    safety_instructions: 'Position on flat ground, light single main fuse and step back 12 meters.',
    safety_tags: ['25 Shots Rapid', 'Golden Willow', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1712',
    code: '1712',
    name: 'Thor - 25 Shots',
    category: 'Aerial Multi-Shots',
    price: 310,
    piece_count: 'Box',
    description: 'Heavy caliber thunder shots with titanium salute bursts lighting up the entire horizon.',
    safety_instructions: 'Maintain 15 meters safe perimeter from all spectators.',
    safety_tags: ['Heavy Caliber', 'Titanium Thunder', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1703',
    code: '1703',
    name: 'Dil Maange More - 50 Shots',
    category: 'Aerial Multi-Shots',
    price: 416,
    piece_count: 'Box',
    description: '50-shot non-stop aerial fiesta with glitter tails, crackling willows, and vibrant color bouquets.',
    safety_instructions: 'Anchor securely. Light and retreat to 15 meters distance.',
    safety_tags: ['50 Shots Fiesta', 'Non-Stop Aerial', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1731',
    code: '1731',
    name: 'Wonder Night - 60 Shots',
    category: 'Aerial Multi-Shots',
    price: 825,
    piece_count: 'Box',
    description: '60-shot sequential multi-color barrage filling the night sky with grand celebratory illumination.',
    safety_instructions: 'Place on wide open field. Step back 20 meters after lighting.',
    safety_tags: ['60 Shots Symphony', 'Sky Illumination', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1744',
    code: '1744',
    name: 'Subha Mangal - 500 Shots',
    category: 'Aerial Multi-Shots',
    price: 7500,
    piece_count: 'Box',
    description: 'Grand finale 500-shot non-stop pyrotechnic display cake transforming midnight into daylight.',
    safety_instructions: 'Professional setup advised. Keep spectators 25 meters away.',
    safety_tags: ['500 Shots Grand Finale', 'Pro-Display', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-1745',
    code: '1745',
    name: 'Sarva Mangal - 1000 Shots',
    category: 'Aerial Multi-Shots',
    price: 15000,
    piece_count: 'Box',
    description: 'The pinnacle of Sivakasi pyrotechnics: 1000 continuous aerial shots with breathtaking multi-tier effects.',
    safety_instructions: 'Anchor with heavy ballast on wide open grounds. Maintain 30m perimeter.',
    safety_tags: ['1000 Shots Pinnacle', 'Maximum Spectacle', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 7. SAFETY MATCHES & NOVELTY MATCHES
  // =========================================================================
  {
    id: 'ayyan-0103-m',
    code: '0103-M',
    name: 'Camel POPS Matches',
    category: 'Safety Matches',
    price: 2090,
    piece_count: '600 Boxes',
    description: 'Safe color-flame friction safety match lights with long burn and moisture-resistant striking heads.',
    safety_instructions: 'Strike gently away from body. Store in dry, cool location.',
    safety_tags: ['Moisture Resistant', 'Color Flame', 'Safety Striker'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0104-m',
    code: '0104-M',
    name: 'Camel NINJA Matches',
    category: 'Safety Matches',
    price: 3595,
    piece_count: '600 Boxes',
    description: 'Heavy glow stormproof ignition matches for fireworks with extended wooden splints.',
    safety_instructions: 'Designed specifically for lighting fireworks fuses safely at distance.',
    safety_tags: ['Stormproof', 'Long Splint', 'Safety Striker'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0205-m',
    code: '0205-M',
    name: 'Ayyan TWYLA Matches 5 Colours',
    category: 'Safety Matches',
    price: 1950,
    piece_count: '600 Boxes',
    description: '5 vibrant color flame friction match lights from Ayyan Fireworks safety series.',
    safety_instructions: 'Keep out of reach of very young children. Strike away from clothing.',
    safety_tags: ['5 Colors Flame', 'Smooth Strike', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },

  // =========================================================================
  // 8. GIFT BOXES / HAMPERS
  // =========================================================================
  {
    id: 'ayyan-0901',
    code: '0901',
    name: 'Ayyan Royal Peacock Family Hamper',
    category: 'Gift Boxes',
    price: 3499,
    piece_count: '45 Items Mega Box',
    description: 'Curated 45-piece luxury family celebration hamper including sparklers, flower pots, chakkars, and multi-shots.',
    safety_instructions: 'Inspect each individual item before lighting. Follow enclosed master safety manual.',
    safety_tags: ['Curated 45 Pcs', 'Family Gift Box', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'ayyan-0902',
    code: '0902',
    name: 'Ayyan Grand Shubh Deepawali VIP Box',
    category: 'Gift Boxes',
    price: 5999,
    piece_count: '70 Items Luxury Box',
    description: 'Grand festive assortment of 70 premium fireworks items with custom velvet packaging and gold foil seals.',
    safety_instructions: 'Follow enclosed individual product safety sheets for each item.',
    safety_tags: ['70 Items Luxury', 'Velvet Gold Pack', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    created_at: new Date().toISOString()
  }
];

// Helper date offset function
export const getFormattedDateOffset = (offsetDays: number = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

// Seed Slot generation for showroom visitations (Visakhapatnam showroom)
export const generateInitialSlots = (): Slot[] => {
  const slots: Slot[] = [];
  const today = new Date();

  for (let d = 0; d < 14; d++) {
    const slotDate = new Date(today);
    slotDate.setDate(today.getDate() + d);
    const dateStr = slotDate.toISOString().split('T')[0];

    const hours = [
      { start: '05:00:00', end: '06:00:00', cap: 120 },
      { start: '06:00:00', end: '07:00:00', cap: 120 },
      { start: '07:00:00', end: '08:00:00', cap: 120 },
      { start: '08:00:00', end: '09:00:00', cap: 120 },
      { start: '09:00:00', end: '10:00:00', cap: 120 },
      { start: '10:00:00', end: '11:00:00', cap: 120 },
      { start: '11:00:00', end: '12:00:00', cap: 120 },
      { start: '12:00:00', end: '13:00:00', cap: 120 },
      { start: '14:00:00', end: '15:00:00', cap: 120 },
      { start: '15:00:00', end: '16:00:00', cap: 120 },
      { start: '16:00:00', end: '17:00:00', cap: 120 },
      { start: '17:00:00', end: '18:00:00', cap: 120 },
      { start: '18:00:00', end: '19:00:00', cap: 120 },
      { start: '19:00:00', end: '20:00:00', cap: 120 },
      { start: '20:00:00', end: '21:00:00', cap: 120 },
      { start: '21:00:00', end: '22:00:00', cap: 120 }
    ];

    hours.forEach((h, index) => {
      slots.push({
        id: `slot-${dateStr}-${index}`,
        slot_date: dateStr,
        start_time: h.start,
        end_time: h.end,
        total_capacity: h.cap,
        booked_capacity: 0,
        is_blocked: false,
        created_at: new Date().toISOString()
      });
    });
  }

  return slots;
};

export const generateInitialBookings = (_slots?: Slot[]): Booking[] => {
  return [];
};
