const fs = require('fs');
const path = require('path');

const PRODUCTS = [
  // =========================================================================
  // 1. MAROONS (Page 1)
  // (Items are priced per 100 packets; 1 unit = 1 packet)
  // =========================================================================
  {
    id: 'ayyan-0801',
    code: '0801',
    name: 'Ganesh Crackers',
    category: 'Maroons',
    price: 36.05,
    piece_count: '1 Packet',
    unit_price: 36.05,
    unit_name: 'packet',
    bundle_rate: 3605.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹3,605.00 / 100 Pkts → ₹36.05 / packet',
    description: 'Authentic Sivakasi traditional red sound maroons with crisp gunpowder report and thunderous echo.',
    safety_instructions: 'Place flat on open ground. Ignite fuse using an agarbatti and retreat immediately to 10 meters distance.',
    safety_tags: ['High Decibel', 'Festive Salute', 'PESO Certified', 'Bunny Brand'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0803',
    code: '0803',
    name: 'Lakshmi Crackers',
    category: 'Maroons',
    price: 20.70,
    piece_count: '1 Packet',
    unit_price: 20.70,
    unit_name: 'packet',
    bundle_rate: 2070.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹2,070.00 / 100 Pkts → ₹20.70 / packet',
    description: 'Classic single-burst festive crackers with loud, sharp report celebrating auspicious beginnings.',
    safety_instructions: 'Light individually in clear open space. Do not ignite inside containers or bottles.',
    safety_tags: ['Auspicious Burst', 'Traditional Formula', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0802',
    code: '0802',
    name: 'Bengal Prince Crackers',
    category: 'Maroons',
    price: 36.05,
    piece_count: '1 Packet',
    unit_price: 36.05,
    unit_name: 'packet',
    bundle_rate: 3605.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹3,605.00 / 100 Pkts → ₹36.05 / packet',
    description: 'Royal-grade sound crackers with supreme decibel clarity and clean detonation report.',
    safety_instructions: 'Keep spectators at minimum 10m clearance. Light from side with cotton garments.',
    safety_tags: ['Royal Grade', 'Crisp Report', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0804',
    code: '0804',
    name: 'King Crackers',
    category: 'Maroons',
    price: 20.70,
    piece_count: '1 Packet',
    unit_price: 20.70,
    unit_name: 'packet',
    bundle_rate: 2070.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹2,070.00 / 100 Pkts → ₹20.70 / packet',
    description: 'High-decibel celebration crackers specially blended for Diwali processions and grand gatherings.',
    safety_instructions: 'Outdoor open ground ignition only. Never bend over cracker during lighting.',
    safety_tags: ['Heavy Report', 'Procession Grade', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0805',
    code: '0805',
    name: 'Jawan Crackers',
    category: 'Maroons',
    price: 16.15,
    piece_count: '1 Packet',
    unit_price: 16.15,
    unit_name: 'packet',
    bundle_rate: 1615.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹1,615.00 / 100 Pkts → ₹16.15 / packet',
    description: 'Medium-range family crackers with reliable fast ignition and lively crackling report.',
    safety_instructions: 'Lay flat on dry concrete or earth. Light and step back 5 meters.',
    safety_tags: ['Family Celebration', 'Quick Burst', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0806',
    code: '0806',
    name: 'Bird Crackers',
    category: 'Maroons',
    price: 8.35,
    piece_count: '1 Packet',
    unit_price: 8.35,
    unit_name: 'packet',
    bundle_rate: 835.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹835.00 / 100 Pkts → ₹8.35 / packet',
    description: 'Compact quick-burst family celebration crackers with sharp crackling sound.',
    safety_instructions: 'Place on ground, light with agarbatti and move to a safe distance.',
    safety_tags: ['Compact Pkts', 'Lively Crackle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 2. SPARKLERS (Page 1)
  // (Calculated per individual stick/piece)
  // =========================================================================
  {
    id: 'ayyan-0101',
    code: '0101',
    name: '7 cm Electric Sparklers',
    category: 'Sparklers',
    price: 11.75,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 1.18,
    unit_name: 'piece',
    bundle_rate: 1175.00,
    bundle_unit: '100 Boxes (1,000 Pcs)',
    unit_breakdown: '₹1,175.00 / 100 Boxes → ₹1.18 / pc (₹11.75 / box)',
    description: 'Pure silver glitter sparklers with smokeless green chemistry formula. Child-safe family favorite.',
    safety_instructions: 'Hold by wire at arms length pointing away from body. Immerse spent wire into bucket of water.',
    safety_tags: ['Smokeless', 'Child Safe', 'Green Chemistry', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0102',
    code: '0102',
    name: '7 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 13.25,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 1.33,
    unit_name: 'piece',
    bundle_rate: 1325.00,
    bundle_unit: '100 Boxes (1,000 Pcs)',
    unit_breakdown: '₹1,325.00 / 100 Boxes → ₹1.33 / pc (₹13.25 / box)',
    description: 'Vibrant multi-colored sparkling handheld sticks with ruby, emerald, and golden stars.',
    safety_instructions: 'Wear cotton clothing. Light one at a time and extinguish spent sticks in water.',
    safety_tags: ['Multi-Colour', 'Vivid Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0103',
    code: '0103',
    name: '9 cm Electric Sparklers',
    category: 'Sparklers',
    price: 13.25,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 1.33,
    unit_name: 'piece',
    bundle_rate: 1325.00,
    bundle_unit: '100 Boxes (1,000 Pcs)',
    unit_breakdown: '₹1,325.00 / 100 Boxes → ₹1.33 / pc (₹13.25 / box)',
    description: 'Extended duration gold and silver sparkling star discharge with uniform bright burn.',
    safety_instructions: 'Hold at arm length. Do not touch glowing wire tip.',
    safety_tags: ['Uniform Burn', 'Bright Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0104',
    code: '0104',
    name: '9 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 15.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 1.50,
    unit_name: 'piece',
    bundle_rate: 1500.00,
    bundle_unit: '100 Boxes (1,000 Pcs)',
    unit_breakdown: '₹1,500.00 / 100 Boxes → ₹1.50 / pc (₹15.00 / box)',
    description: 'Rich emerald, ruby, and golden star bursts designed for family festive moments.',
    safety_instructions: 'Keep water bucket nearby. Never wave near clothing or hair.',
    safety_tags: ['Vibrant Hues', 'Low Smoke', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0105',
    code: '0105',
    name: '10 cm Ruby Sparklers',
    category: 'Sparklers',
    price: 21.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 2.10,
    unit_name: 'piece',
    bundle_rate: 210.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹210.00 / 10 Boxes → ₹2.10 / pc (₹21.00 / box)',
    description: 'Deep ruby crimson sparkling glow with intense luminosity and minimal smoke.',
    safety_instructions: 'Hold firmly by wire base. Dip in water after use.',
    safety_tags: ['Ruby Red', 'High Luminosity', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0109',
    code: '0109',
    name: '12 cm Electric Sparklers',
    category: 'Sparklers',
    price: 18.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 1.80,
    unit_name: 'piece',
    bundle_rate: 180.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹180.00 / 10 Boxes → ₹1.80 / pc (₹18.00 / box)',
    description: 'Brilliant white electric sparklers with steady, continuous sparkling cascade.',
    safety_instructions: 'Outdoor use recommended. Light with agarbatti or candle.',
    safety_tags: ['Bright White', 'Steady Burn', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0110',
    code: '0110',
    name: '12 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 24.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 2.40,
    unit_name: 'piece',
    bundle_rate: 240.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹240.00 / 10 Boxes → ₹2.40 / pc (₹24.00 / box)',
    description: '4-color shifting dazzling handheld fireworks with emerald, sapphire, and gold sparks.',
    safety_instructions: 'Hold at arm length. Extinguish spent rods in water.',
    safety_tags: ['4-Color Shift', 'Extended Flame', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0111',
    code: '0111',
    name: '15 cm Electric Sparklers',
    category: 'Sparklers',
    price: 40.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 4.00,
    unit_name: 'piece',
    bundle_rate: 400.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹400.00 / 10 Boxes → ₹4.00 / pc (₹40.00 / box)',
    description: 'Long glitter sticks ideal for weddings, temple entrances, and grand Diwali evening displays.',
    safety_instructions: 'Maintain 2 meters distance from others. Do not touch hot wire.',
    safety_tags: ['Grand Entrance', 'Long Burn', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0112',
    code: '0112',
    name: '15 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 53.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 5.30,
    unit_name: 'piece',
    bundle_rate: 530.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹530.00 / 10 Boxes → ₹5.30 / pc (₹53.00 / box)',
    description: 'Heavy multi-color sparkle discharge with long burning time and brilliant flare.',
    safety_instructions: 'Extinguish wire in water bucket immediately after burn ends.',
    safety_tags: ['Heavy Discharge', 'Multi-Color', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0113',
    code: '0113',
    name: '15 cm Ruby Sparklers',
    category: 'Sparklers',
    price: 45.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 4.50,
    unit_name: 'piece',
    bundle_rate: 450.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹450.00 / 10 Boxes → ₹4.50 / pc (₹45.00 / box)',
    description: 'Intense ruby red glowing handheld sparklers with rich color saturation.',
    safety_instructions: 'Light from side. Extinguish in water.',
    safety_tags: ['Ruby Sparkle', 'Rich Color', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0115',
    code: '0115',
    name: '15 cm Panchavarnam 5 In One',
    category: 'Sparklers',
    price: 46.00,
    piece_count: '1 Box (10 Pcs)',
    unit_price: 4.60,
    unit_name: 'piece',
    bundle_rate: 460.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹460.00 / 10 Boxes → ₹4.60 / pc (₹46.00 / box)',
    description: '5 distinct sequential color transformations in a single sparkle stick: red, gold, green, blue, and silver.',
    safety_instructions: 'Hold at arm length pointing away from body. Keep in sight until spent.',
    safety_tags: ['Panchavarnam', '5-Color Shift', 'Iconic Ayyan', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0116',
    code: '0116',
    name: '30 cm Electric Sparklers',
    category: 'Sparklers',
    price: 40.00,
    piece_count: '1 Box (5 Pcs)',
    unit_price: 8.00,
    unit_name: 'piece',
    bundle_rate: 400.00,
    bundle_unit: '10 Boxes (50 Pcs)',
    unit_breakdown: '₹400.00 / 10 Boxes → ₹8.00 / pc (₹40.00 / box)',
    description: 'Extra-long mega burning family sparkler sticks with dense golden sparks for over 90 seconds.',
    safety_instructions: 'Adult supervision required. Always discard wire in water bucket.',
    safety_tags: ['30cm Mega', '90s Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0117',
    code: '0117',
    name: '30 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 53.00,
    piece_count: '1 Box (5 Pcs)',
    unit_price: 10.60,
    unit_name: 'piece',
    bundle_rate: 530.00,
    bundle_unit: '10 Boxes (50 Pcs)',
    unit_breakdown: '₹530.00 / 10 Boxes → ₹10.60 / pc (₹53.00 / box)',
    description: '30cm giant colored sparklers showering deep ruby and emerald stars in wide radii.',
    safety_instructions: 'Keep 2m clearance. Do not inhale smoke directly.',
    safety_tags: ['30cm Colored', 'Vivid Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0118',
    code: '0118',
    name: '50 cm Electric Sparklers',
    category: 'Sparklers',
    price: 102.00,
    piece_count: '1 Box (5 Pcs)',
    unit_price: 20.40,
    unit_name: 'piece',
    bundle_rate: 1020.00,
    bundle_unit: '10 Boxes (50 Pcs)',
    unit_breakdown: '₹1,020.00 / 10 Boxes → ₹20.40 / pc (₹102.00 / box)',
    description: 'Giant 50cm sparklers with over 3 minutes of continuous burn and towering sparkling canopy.',
    safety_instructions: 'Hold with two hands if needed. Place spent rod into water immediately.',
    safety_tags: ['50cm Giant', '3 Min Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0119',
    code: '0119',
    name: '50 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 126.00,
    piece_count: '1 Box (5 Pcs)',
    unit_price: 25.20,
    unit_name: 'piece',
    bundle_rate: 1260.00,
    bundle_unit: '10 Boxes (50 Pcs)',
    unit_breakdown: '₹1,260.00 / 10 Boxes → ₹25.20 / pc (₹126.00 / box)',
    description: 'Mega 50cm multi-color sparkler sticks delivering extended color brilliance.',
    safety_instructions: 'Hold at safe distance. Never touch heated rod.',
    safety_tags: ['50cm Multi-Color', 'Towering Canopy', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0120',
    code: '0120',
    name: '75 cm Electric Sparklers',
    category: 'Sparklers',
    price: 170.00,
    piece_count: '1 Box (5 Pcs)',
    unit_price: 34.00,
    unit_name: 'piece',
    bundle_rate: 1700.00,
    bundle_unit: '10 Boxes (50 Pcs)',
    unit_breakdown: '₹1,700.00 / 10 Boxes → ₹34.00 / pc (₹170.00 / box)',
    description: 'Giant 75cm mega handheld fireworks creating immense silver sparkles for over 4 minutes.',
    safety_instructions: 'Adults only. Ensure ample outdoor open space.',
    safety_tags: ['75cm Mega', '4 Min Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0121',
    code: '0121',
    name: '75 cm Coloured Sparklers',
    category: 'Sparklers',
    price: 205.00,
    piece_count: '1 Box (5 Pcs)',
    unit_price: 41.00,
    unit_name: 'piece',
    bundle_rate: 2050.00,
    bundle_unit: '10 Boxes (50 Pcs)',
    unit_breakdown: '₹2,050.00 / 10 Boxes → ₹41.00 / pc (₹205.00 / box)',
    description: 'Supreme 75cm multi-color giant sparkler sticks with grand panoramic brilliance.',
    safety_instructions: 'Hold securely. Discard in large water bucket.',
    safety_tags: ['75cm Giant Color', 'Supreme Brilliance', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0123',
    code: '0123',
    name: 'Rajadhani Sparklers (5 Varieties)',
    category: 'Sparklers',
    price: 47.60,
    piece_count: '1 Box',
    unit_price: 47.60,
    unit_name: 'box',
    bundle_rate: 238.00,
    bundle_unit: 'Pack of 5 Boxes',
    unit_breakdown: '₹238.00 / pack (5 Boxes) → ₹47.60 / box',
    description: 'Assorted collection box featuring 5 premium distinct sparkler varieties in a single royal gift pack.',
    safety_instructions: 'Keep in dry place. Light with cotton garments only.',
    safety_tags: ['5 Varieties', 'Gift Edition', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 3. GROUND CHAKKARS & WHEELS (Page 2)
  // (Calculated per individual single chakkar / spinner)
  // =========================================================================
  {
    id: 'ayyan-0201',
    code: '0201',
    name: 'Ground Chakkar Medium',
    category: 'Ground Chakkars',
    price: 2.48,
    piece_count: '1 Piece',
    unit_price: 2.48,
    unit_name: 'piece',
    bundle_rate: 248.00,
    bundle_unit: '4 Boxes (100 Pcs)',
    unit_breakdown: '₹248.00 / 4 Boxes → ₹2.48 / piece',
    description: 'High-speed golden rotating wheel creating circular rings of bright starlight on smooth ground.',
    safety_instructions: 'Place on smooth, flat dry surface with arrow pointing upward. Light fuse at edge and step back.',
    safety_tags: ['High RPM', 'Golden Aura', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0202',
    code: '0202',
    name: 'Ground Chakkar Big',
    category: 'Ground Chakkars',
    price: 3.50,
    piece_count: '1 Piece',
    unit_price: 3.50,
    unit_name: 'piece',
    bundle_rate: 350.00,
    bundle_unit: '4 Boxes (100 Pcs)',
    unit_breakdown: '₹350.00 / 4 Boxes → ₹3.50 / piece',
    description: 'Wide-radius silver spinner with rapid rotational velocity and long-lasting fiery spiral ring.',
    safety_instructions: 'Ensure 3 meters radius around the spinner is free of dry leaves or flammable materials.',
    safety_tags: ['Wide Radius', 'Silver Rings', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0203',
    code: '0203',
    name: 'Ground Chakkar Special',
    category: 'Ground Chakkars',
    price: 8.20,
    piece_count: '1 Piece',
    unit_price: 8.20,
    unit_name: 'piece',
    bundle_rate: 820.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹820.00 / 10 Boxes → ₹8.20 / piece',
    description: 'Special dual-phase long-running sparkling ground spinner with color sparks.',
    safety_instructions: 'Place on flat cement or tile surface. Clear 4 meters.',
    safety_tags: ['Dual-Phase', 'Long Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0204',
    code: '0204',
    name: 'Ground Chakkar Deluxe',
    category: 'Ground Chakkars',
    price: 14.50,
    piece_count: '1 Piece',
    unit_price: 14.50,
    unit_name: 'piece',
    bundle_rate: 1450.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,450.00 / 10 Boxes → ₹14.50 / piece',
    description: 'Deluxe dual-color rotational fireworks wheel spinning for over 45 seconds with wide gold rings.',
    safety_instructions: 'Place flat. Ignite fuse and retreat 5 meters.',
    safety_tags: ['Deluxe Gold', '45s Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0205',
    code: '0205',
    name: 'Krishna Chakkar Big',
    category: 'Ground Chakkars',
    price: 4.40,
    piece_count: '1 Piece',
    unit_price: 4.40,
    unit_name: 'piece',
    bundle_rate: 440.00,
    bundle_unit: '4 Boxes (100 Pcs)',
    unit_breakdown: '₹440.00 / 4 Boxes → ₹4.40 / piece',
    description: 'Legendary Bunny Brand Krishna design with brilliant luminescent spinning halo.',
    safety_instructions: 'Light with agarbatti and step back.',
    safety_tags: ['Krishna Halo', 'Bunny Brand', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0206',
    code: '0206',
    name: 'Krishna Chakkar Special',
    category: 'Ground Chakkars',
    price: 8.60,
    piece_count: '1 Piece',
    unit_price: 8.60,
    unit_name: 'piece',
    bundle_rate: 860.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹860.00 / 10 Boxes → ₹8.60 / piece',
    description: 'Extended duration rotating ground fireworks producing a mesmerizing sacred chakra ring of gold.',
    safety_instructions: 'Flat ground placement only. Clear 5 meters.',
    safety_tags: ['Sacred Chakra', 'Extended Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0209',
    code: '0209',
    name: 'Joke Wheel',
    category: 'Wheels',
    price: 20.60,
    piece_count: '1 Piece',
    unit_price: 20.60,
    unit_name: 'piece',
    bundle_rate: 103.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹103.00 / box (5 Pcs) → ₹20.60 / piece',
    description: 'Whimsical spinning wheel with surprise crackling finish and jumping stars.',
    safety_instructions: 'Mount with nail or place securely. Step back 5m.',
    safety_tags: ['Surprise Crackle', 'Jumping Stars', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0210',
    code: '0210',
    name: 'Star Wheel',
    category: 'Wheels',
    price: 20.60,
    piece_count: '1 Piece',
    unit_price: 20.60,
    unit_name: 'piece',
    bundle_rate: 103.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹103.00 / box (5 Pcs) → ₹20.60 / piece',
    description: 'Brilliant star-shaped spinning ground wheel with radiating gold spokes.',
    safety_instructions: 'Place on level surface. Retreat 5m.',
    safety_tags: ['Star Spokes', 'Radiating Gold', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0211',
    code: '0211',
    name: 'Classic Wheel',
    category: 'Wheels',
    price: 8.80,
    piece_count: '1 Piece',
    unit_price: 8.80,
    unit_name: 'piece',
    bundle_rate: 88.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹88.00 / box (10 Pcs) → ₹8.80 / piece',
    description: 'High rotational speed with gold aura and smooth balanced spin.',
    safety_instructions: 'Clear 3m radius.',
    safety_tags: ['High RPM', 'Balanced Spin', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0212',
    code: '0212',
    name: 'Whistling Wheel',
    category: 'Wheels',
    price: 17.40,
    piece_count: '1 Piece',
    unit_price: 17.40,
    unit_name: 'piece',
    bundle_rate: 174.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹174.00 / box (10 Pcs) → ₹17.40 / piece',
    description: 'Auditory spinning wheel producing a pleasant musical whistle throughout its rotation.',
    safety_instructions: 'Outdoor ground use only. Step back 5m.',
    safety_tags: ['Musical Whistle', 'Auditory Effect', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0215',
    code: '0215',
    name: 'Glittering Wheel',
    category: 'Wheels',
    price: 22.40,
    piece_count: '1 Piece',
    unit_price: 22.40,
    unit_name: 'piece',
    bundle_rate: 112.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹112.00 / box (5 Pcs) → ₹22.40 / piece',
    description: 'Multi-color glittering rotation effect with diamond flashes.',
    safety_instructions: 'Light fuse and retreat 5m.',
    safety_tags: ['Glittering Flashes', 'Multi-Color', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0216',
    code: '0216',
    name: 'Tinto Wheel (Red & White)',
    category: 'Wheels',
    price: 20.00,
    piece_count: '1 Piece',
    unit_price: 20.00,
    unit_name: 'piece',
    bundle_rate: 100.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹100.00 / box (5 Pcs) → ₹20.00 / piece',
    description: 'Dynamic red and silver white dual-tone rotating wheel creating concentric rings.',
    safety_instructions: 'Place flat on open ground.',
    safety_tags: ['Red & White', 'Concentric Rings', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0219',
    code: '0219',
    name: 'Rio Wheel (Orange & Purple)',
    category: 'Wheels',
    price: 20.00,
    piece_count: '1 Piece',
    unit_price: 20.00,
    unit_name: 'piece',
    bundle_rate: 100.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹100.00 / box (5 Pcs) → ₹20.00 / piece',
    description: 'Exotic orange and purple neon sparkling wheel spinning at high velocity.',
    safety_instructions: 'Light with agarbatti and step back.',
    safety_tags: ['Orange & Purple', 'High Velocity', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0221',
    code: '0221',
    name: 'Lotus Wheel',
    category: 'Wheels',
    price: 14.00,
    piece_count: '1 Piece',
    unit_price: 14.00,
    unit_name: 'piece',
    bundle_rate: 70.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹70.00 / box (5 Pcs) → ₹14.00 / piece',
    description: 'Petal-shaped floral fountain spinner mimicking a blooming lotus flower in gold.',
    safety_instructions: 'Place on smooth ground. Retreat 5m.',
    safety_tags: ['Blooming Lotus', 'Floral Petals', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0222',
    code: '0222',
    name: 'Cocktail Spinners',
    category: 'Wheels',
    price: 2.70,
    piece_count: '1 Piece',
    unit_price: 2.70,
    unit_name: 'piece',
    bundle_rate: 27.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹27.00 / box (10 Pcs) → ₹2.70 / piece',
    description: 'Compact rapid ground spinners buzzing with colorful sparkling aura.',
    safety_instructions: 'Place flat and ignite. Clear 3m.',
    safety_tags: ['Cocktail Spinner', 'Rapid Buzz', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 4. FOUNTAINS & FLOWER POTS (Pages 2 & 3)
  // (Calculated per individual flower pot / fountain cone)
  // =========================================================================
  {
    id: 'ayyan-0301',
    code: '0301',
    name: 'Flower Pots Small',
    category: 'Flower Pots',
    price: 5.00,
    piece_count: '1 Piece',
    unit_price: 5.00,
    unit_name: 'piece',
    bundle_rate: 500.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹500.00 / 10 Boxes → ₹5.00 / piece',
    description: 'Golden shower fountain shooting 8 feet high with glittering star cascade.',
    safety_instructions: 'Place upright on flat earth. Light top tip and retreat 4 meters.',
    safety_tags: ['8ft Golden Canopy', 'Low Smoke', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0302',
    code: '0302',
    name: 'Flower Pots Big',
    category: 'Flower Pots',
    price: 8.00,
    piece_count: '1 Piece',
    unit_price: 8.00,
    unit_name: 'piece',
    bundle_rate: 800.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹800.00 / 10 Boxes → ₹8.00 / piece',
    description: 'Volcanic gold and silver sparkling shower with wide canopy shooting 12 feet high.',
    safety_instructions: 'Ensure vertical placement. Keep clearance overhead from tree branches.',
    safety_tags: ['12ft Canopy', 'Volcanic Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0303',
    code: '0303',
    name: 'Flower Pots Special',
    category: 'Flower Pots',
    price: 12.50,
    piece_count: '1 Piece',
    unit_price: 12.50,
    unit_name: 'piece',
    bundle_rate: 1250.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,250.00 / 10 Boxes → ₹12.50 / piece',
    description: 'Extra high sparkling canopy cone fountain reaching up to 15 feet with thick gold palm tails.',
    safety_instructions: 'Outdoor open sky only. Retreat 6 meters.',
    safety_tags: ['15ft High Spray', 'Gold Palm Tails', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0304',
    code: '0304',
    name: 'Flower Pots Giant',
    category: 'Flower Pots',
    price: 26.50,
    piece_count: '1 Piece',
    unit_price: 26.50,
    unit_name: 'piece',
    bundle_rate: 265.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹265.00 / box (10 Pcs) → ₹26.50 / piece',
    description: 'Towering 20-foot sparkling fountain spray raining gold and titanium silver stars for over 40 seconds.',
    safety_instructions: 'Position on flat stone/pavement. Clear 8 meters.',
    safety_tags: ['20ft Giant', '40s Duration', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0305',
    code: '0305',
    name: 'Flower Pots Deluxe (2 Pcs)',
    category: 'Flower Pots',
    price: 42.50,
    piece_count: '1 Piece',
    unit_price: 42.50,
    unit_name: 'piece',
    bundle_rate: 85.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹85.00 / box (2 Pcs) → ₹42.50 / piece',
    description: 'Heavy caliber deluxe flower pot shooting high-density golden palm canopies.',
    safety_instructions: 'Stand clear 6 meters.',
    safety_tags: ['Deluxe Caliber', 'Dense Canopy', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0306',
    code: '0306',
    name: 'Flower Pots Deluxe (5 Pcs)',
    category: 'Flower Pots',
    price: 36.00,
    piece_count: '1 Piece',
    unit_price: 36.00,
    unit_name: 'piece',
    bundle_rate: 180.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹180.00 / box (5 Pcs) → ₹36.00 / piece',
    description: '5-pack value deluxe flower pots with extended burning duration and thick glitter.',
    safety_instructions: 'Light top fuse and step back.',
    safety_tags: ['5 Pack Value', 'Thick Glitter', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0307',
    code: '0307',
    name: 'Flower Pots Red',
    category: 'Flower Pots',
    price: 14.30,
    piece_count: '1 Piece',
    unit_price: 14.30,
    unit_name: 'piece',
    bundle_rate: 1430.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,430.00 / 10 Boxes → ₹14.30 / piece',
    description: 'Deep ruby crimson sparkling shower with emerald strobes interspersed throughout.',
    safety_instructions: 'Maintain 6m clearance.',
    safety_tags: ['Crimson Red', 'Emerald Strobes', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0309',
    code: '0309',
    name: 'Tri Colour Fountain',
    category: 'Colourful Fountains',
    price: 43.00,
    piece_count: '1 Piece',
    unit_price: 43.00,
    unit_name: 'piece',
    bundle_rate: 215.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹215.00 / box (5 Pcs) → ₹43.00 / piece',
    description: 'Three distinct sequential color bursts transitioning smoothly from orange to white to green.',
    safety_instructions: 'Place upright. Clear 6 meters.',
    safety_tags: ['Tri-Color Indian Flare', '3-Stage Fountain', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0310',
    code: '0310',
    name: 'Rangoli Fountain',
    category: 'Colourful Fountains',
    price: 27.20,
    piece_count: '1 Piece',
    unit_price: 27.20,
    unit_name: 'piece',
    bundle_rate: 136.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹136.00 / box (5 Pcs) → ₹27.20 / piece',
    description: 'Floral pattern sparkling stage fountain spreading wide symmetrical fan-shaped color sparks.',
    safety_instructions: 'Place on wide flat surface. Retreat 5m.',
    safety_tags: ['Floral Rangoli', 'Symmetrical Fan', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0325',
    code: '0325',
    name: 'Colour Koti Deluxe',
    category: 'Colourful Fountains',
    price: 36.80,
    piece_count: '1 Piece',
    unit_price: 36.80,
    unit_name: 'piece',
    bundle_rate: 368.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹368.00 / box (10 Pcs) → ₹36.80 / piece',
    description: 'High power mega canopy fountain shooting dense color stars over 15 feet.',
    safety_instructions: 'Outdoor open area only.',
    safety_tags: ['Colour Koti', '15ft Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0311',
    code: '0311',
    name: 'Jadugar Stage Fountain',
    category: 'Colourful Fountains',
    price: 38.75,
    piece_count: '1 Piece',
    unit_price: 38.75,
    unit_name: 'piece',
    bundle_rate: 155.00,
    bundle_unit: '1 Box (4 Pcs)',
    unit_breakdown: '₹155.00 / box (4 Pcs) → ₹38.75 / piece',
    description: 'Multi-color morphing stage fountain transitioning from ruby red to emerald green and sapphire blue.',
    safety_instructions: 'Keep spectators at 5m distance.',
    safety_tags: ['Color Morphing', 'Stage Effect', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0312',
    code: '0312',
    name: 'Manoranjan Fountain',
    category: 'Colourful Fountains',
    price: 38.75,
    piece_count: '1 Piece',
    unit_price: 38.75,
    unit_name: 'piece',
    bundle_rate: 155.00,
    bundle_unit: '1 Box (4 Pcs)',
    unit_breakdown: '₹155.00 / box (4 Pcs) → ₹38.75 / piece',
    description: 'Colorful family celebration stage effect with gold stars and crackling audio flourishes.',
    safety_instructions: 'Place on firm surface. Light and retreat.',
    safety_tags: ['Family Celebration', 'Crackling Flourish', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0313',
    code: '0313',
    name: 'Roopkhela Fountain',
    category: 'Colourful Fountains',
    price: 27.00,
    piece_count: '1 Piece',
    unit_price: 27.00,
    unit_name: 'piece',
    bundle_rate: 270.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹270.00 / box (10 Pcs) → ₹27.00 / piece',
    description: 'Multi-shade sparkling fountain throwing vibrant floral arcs.',
    safety_instructions: 'Light top tip. Step back 5m.',
    safety_tags: ['Floral Arcs', 'Multi-Shade', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0314',
    code: '0314',
    name: 'Varnajal Fountain',
    category: 'Colourful Fountains',
    price: 24.20,
    piece_count: '1 Piece',
    unit_price: 24.20,
    unit_name: 'piece',
    bundle_rate: 242.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹242.00 / box (10 Pcs) → ₹24.20 / piece',
    description: 'Vibrant shower cascade creating a dense curtain of sparkling colored fire.',
    safety_instructions: 'Flat ground only.',
    safety_tags: ['Curtain of Fire', 'Dense Shower', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0315',
    code: '0315',
    name: "Kiddy's Joy (5 in One)",
    category: 'Colourful Fountains',
    price: 93.00,
    piece_count: '1 Piece',
    unit_price: 93.00,
    unit_name: 'piece',
    bundle_rate: 93.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹93.00 / box (1 Pce) → ₹93.00 / piece',
    description: '5-in-1 sequential color changing stage fountain designed for family joy.',
    safety_instructions: 'Keep children at 5m distance.',
    safety_tags: ['5 in One', 'Child Friendly', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0318',
    code: '0318',
    name: 'Super Star (Crackling)',
    category: 'Colourful Fountains',
    price: 12.40,
    piece_count: '1 Piece',
    unit_price: 12.40,
    unit_name: 'piece',
    bundle_rate: 62.00,
    bundle_unit: '5 Boxes (5 Pcs)',
    unit_breakdown: '₹62.00 / 5 Boxes → ₹12.40 / piece',
    description: 'Sharp crackling star fountain with energetic snapping reports.',
    safety_instructions: 'Place upright. Clear 4m.',
    safety_tags: ['Crackling Stars', 'Energetic Snap', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0320',
    code: '0320',
    name: 'Dil Se Fountain',
    category: 'Colourful Fountains',
    price: 118.00,
    piece_count: '1 Piece',
    unit_price: 118.00,
    unit_name: 'piece',
    bundle_rate: 236.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹236.00 / box (2 Pcs) → ₹118.00 / piece',
    description: 'Heartwarming 2-stage mega fountain spraying crimson glitter and golden showers.',
    safety_instructions: 'Retreat 6m.',
    safety_tags: ['Heartwarming Spray', 'Crimson Glitter', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0324',
    code: '0324',
    name: 'Yolo Green Fountain',
    category: 'Colourful Fountains',
    price: 88.33,
    piece_count: '1 Piece',
    unit_price: 88.33,
    unit_name: 'piece',
    bundle_rate: 265.00,
    bundle_unit: '1 Box (3 Pcs)',
    unit_breakdown: '₹265.00 / box (3 Pcs) → ₹88.33 / piece',
    description: 'Luminous emerald green volcanic fountain shooting thick green pearls 12 feet high.',
    safety_instructions: 'Clear 6m radius.',
    safety_tags: ['Emerald Green', '12ft Fountain', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0326',
    code: '0326',
    name: 'Pure Gold Fountain',
    category: 'Colourful Fountains',
    price: 37.00,
    piece_count: '1 Piece',
    unit_price: 37.00,
    unit_name: 'piece',
    bundle_rate: 74.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹74.00 / box (2 Pcs) → ₹37.00 / piece',
    description: 'Pure 24k-gold shimmering spray with dense micro-sparks.',
    safety_instructions: 'Light and step back.',
    safety_tags: ['24k Gold Spray', 'Micro-Sparks', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0322',
    code: '0322',
    name: 'Fire Drops Fountain',
    category: 'Colourful Fountains',
    price: 37.00,
    piece_count: '1 Piece',
    unit_price: 37.00,
    unit_name: 'piece',
    bundle_rate: 74.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹74.00 / box (2 Pcs) → ₹37.00 / piece',
    description: 'Cascading golden rain drops with red strobe accents showering gently.',
    safety_instructions: 'Place on level stone.',
    safety_tags: ['Golden Rain', 'Red Strobes', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0323',
    code: '0323',
    name: 'Snow Patrol Fountain',
    category: 'Colourful Fountains',
    price: 32.00,
    piece_count: '1 Piece',
    unit_price: 32.00,
    unit_name: 'piece',
    bundle_rate: 32.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹32.00 / box (1 Pce) → ₹32.00 / piece',
    description: 'Silver white sparkling shower effect mimicking falling snow flakes in winter.',
    safety_instructions: 'Outdoor ground only.',
    safety_tags: ['Silver Snow', 'Cool Strobe', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0327',
    code: '0327',
    name: 'Purple Dove Fountain',
    category: 'Colourful Fountains',
    price: 32.00,
    piece_count: '1 Piece',
    unit_price: 32.00,
    unit_name: 'piece',
    bundle_rate: 32.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹32.00 / box (1 Pce) → ₹32.00 / piece',
    description: 'Gentle royal purple sparkling spray with soft white comet accents.',
    safety_instructions: 'Light top fuse. Step back 4m.',
    safety_tags: ['Royal Purple', 'Gentle Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1319',
    code: '1319',
    name: 'Crackling Star Fountain',
    category: 'Colourful Fountains',
    price: 32.00,
    piece_count: '1 Piece',
    unit_price: 32.00,
    unit_name: 'piece',
    bundle_rate: 32.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹32.00 / box (1 Pce) → ₹32.00 / piece',
    description: 'High-density crackling star cone fountain filling the night with snappy golden sparklers.',
    safety_instructions: 'Retreat 5m.',
    safety_tags: ['Crackling Star', 'Snappy Golden', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1320',
    code: '1320',
    name: 'Chhota Bhai (Mini Siren)',
    category: 'Colourful Fountains',
    price: 37.00,
    piece_count: '1 Piece',
    unit_price: 37.00,
    unit_name: 'piece',
    bundle_rate: 185.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹185.00 / box (5 Pcs) → ₹37.00 / piece',
    description: 'Mini auditory acoustic siren fountain with flashing red and green strobes.',
    safety_instructions: 'Outdoor open space only.',
    safety_tags: ['Mini Siren', 'Acoustic Whistle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1321',
    code: '1321',
    name: 'Super Sonica Siren',
    category: 'Colourful Fountains',
    price: 18.60,
    piece_count: '1 Piece',
    unit_price: 18.60,
    unit_name: 'piece',
    bundle_rate: 93.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹93.00 / box (5 Pcs) → ₹18.60 / piece',
    description: 'High frequency acoustic whistle siren with bright silver star flare.',
    safety_instructions: 'Clear 5m perimeter.',
    safety_tags: ['Sonic Siren', 'Silver Flare', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0328',
    code: '0328',
    name: 'Senorita Fountain',
    category: 'Colourful Fountains',
    price: 48.33,
    piece_count: '1 Piece',
    unit_price: 48.33,
    unit_name: 'piece',
    bundle_rate: 145.00,
    bundle_unit: '1 Box (3 Pcs)',
    unit_breakdown: '₹145.00 / box (3 Pcs) → ₹48.33 / piece',
    description: 'Graceful dancing multi-color floral fountain with ruby and amber petals.',
    safety_instructions: 'Place firmly. Step back 5m.',
    safety_tags: ['Dancing Fountain', 'Amber Petals', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0329',
    code: '0329',
    name: 'Tuti Fruti (1 Pce Crackling)',
    category: 'Colourful Fountains',
    price: 39.00,
    piece_count: '1 Piece',
    unit_price: 39.00,
    unit_name: 'piece',
    bundle_rate: 117.00,
    bundle_unit: '1 Box (3 Pcs)',
    unit_breakdown: '₹117.00 / box (3 Pcs) → ₹39.00 / piece',
    description: 'Fruit punch inspired multi-color crackling fountain with vivid pastel bursts.',
    safety_instructions: 'Light top and retreat 5m.',
    safety_tags: ['Fruit Punch Colors', 'Pastel Bursts', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0330',
    code: '0330',
    name: 'Orange Crush Fountain',
    category: 'Colourful Fountains',
    price: 32.60,
    piece_count: '1 Piece',
    unit_price: 32.60,
    unit_name: 'piece',
    bundle_rate: 163.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹163.00 / box (5 Pcs) → ₹32.60 / piece',
    description: 'Vivid citrus orange glowing fountain shooting dense amber stars.',
    safety_instructions: 'Clear 4m.',
    safety_tags: ['Citrus Orange', 'Amber Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0331',
    code: '0331',
    name: 'Code Red Fountain',
    category: 'Colourful Fountains',
    price: 155.00,
    piece_count: '1 Piece',
    unit_price: 155.00,
    unit_name: 'piece',
    bundle_rate: 155.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹155.00 / box (1 Pce) → ₹155.00 / piece',
    description: 'Intense crimson emergency flare fountain soaring 15 feet with thick ruby spray.',
    safety_instructions: 'Outdoor open field only.',
    safety_tags: ['Code Red', '15ft Ruby Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0332',
    code: '0332',
    name: 'Golden Dawn (Peacock Gold)',
    category: 'Colourful Fountains',
    price: 110.00,
    piece_count: '1 Piece',
    unit_price: 110.00,
    unit_name: 'piece',
    bundle_rate: 110.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹110.00 / box (1 Pce) → ₹110.00 / piece',
    description: 'Broad fan-shaped golden peacock plumage spray with dense golden sparks.',
    safety_instructions: 'Position on flat ground. Step back 6m.',
    safety_tags: ['Peacock Gold', 'Plumage Spray', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0333',
    code: '0333',
    name: 'Indigo Surprise (Peacock Purple)',
    category: 'Colourful Fountains',
    price: 135.00,
    piece_count: '1 Piece',
    unit_price: 135.00,
    unit_name: 'piece',
    bundle_rate: 135.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹135.00 / box (1 Pce) → ₹135.00 / piece',
    description: 'Vivid indigo and royal purple peacock fan fountain with dazzling silver eyelets.',
    safety_instructions: 'Clear 6m perimeter.',
    safety_tags: ['Peacock Purple', 'Indigo Surprise', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0335',
    code: '0335',
    name: 'Tora Tora (Colour & Crackling)',
    category: 'Colourful Fountains',
    price: 40.00,
    piece_count: '1 Piece',
    unit_price: 40.00,
    unit_name: 'piece',
    bundle_rate: 200.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹200.00 / box (5 Pcs) → ₹40.00 / piece',
    description: 'Energetic dual-action color spray with rapid-fire titanium crackles.',
    safety_instructions: 'Step back 5m.',
    safety_tags: ['Dual-Action', 'Titanium Crackle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0336',
    code: '0336',
    name: 'Mega Peacock Stage Fountain',
    category: 'Colourful Fountains',
    price: 288.00,
    piece_count: '1 Piece',
    unit_price: 288.00,
    unit_name: 'piece',
    bundle_rate: 288.00,
    bundle_unit: '1 Box (1 Pce)',
    unit_breakdown: '₹288.00 / box (1 Pce) → ₹288.00 / piece',
    description: 'Broad multi-nozzle fan fountain mimicking the majestic display of a peacock spreading its feathers in emerald and gold fire.',
    safety_instructions: 'Maintain 8 meters safety perimeter. Orient the wide nozzle arc facing the audience.',
    safety_tags: ['Mega Peacock', 'Multi-Nozzle Fan', 'Grand Stage Finale', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 5. NOVELTY FIREWORKS & TORCHES (Page 3)
  // (Calculated per individual unit)
  // =========================================================================
  {
    id: 'ayyan-0401',
    code: '0401',
    name: 'Twinkling Star 45 cms',
    category: 'Novelties',
    price: 3.00,
    piece_count: '1 Piece',
    unit_price: 3.00,
    unit_name: 'piece',
    bundle_rate: 300.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹300.00 / 10 Boxes → ₹3.00 / piece',
    description: '45cm handheld flashing strobe wand flashing bright silver stars.',
    safety_instructions: 'Hold by plastic end at arm length.',
    safety_tags: ['45cm Strobe', 'Twinkling Star', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0402',
    code: '0402',
    name: 'Twinkling Star 60 cms',
    category: 'Novelties',
    price: 4.70,
    piece_count: '1 Piece',
    unit_price: 4.70,
    unit_name: 'piece',
    bundle_rate: 470.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹470.00 / 10 Boxes → ₹4.70 / piece',
    description: '60cm extended twinkling strobe torch with high-visibility silver strobes.',
    safety_instructions: 'Dip spent wire in water.',
    safety_tags: ['60cm Strobe', 'High Visibility', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0403',
    code: '0403',
    name: 'Twinkling Star 120 cms',
    category: 'Novelties',
    price: 10.00,
    piece_count: '1 Piece',
    unit_price: 10.00,
    unit_name: 'piece',
    bundle_rate: 1000.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,000.00 / 10 Boxes → ₹10.00 / piece',
    description: 'Giant 120cm mega strobe torch burning for over 2 minutes.',
    safety_instructions: 'Hold with two hands. Keep away from face.',
    safety_tags: ['120cm Mega Torch', '2 Min Strobe', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0406',
    code: '0406',
    name: 'Electric Diamond',
    category: 'Novelties',
    price: 1.88,
    piece_count: '1 Piece',
    unit_price: 1.88,
    unit_name: 'piece',
    bundle_rate: 188.00,
    bundle_unit: '4 Boxes (100 Pcs)',
    unit_breakdown: '₹188.00 / 4 Boxes → ₹1.88 / piece',
    description: 'Diamond-shaped sparkling novelty producing crisp electric silver flashes.',
    safety_instructions: 'Place on ground, light and step back.',
    safety_tags: ['Electric Diamond', 'Silver Flashes', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0501',
    code: '0501',
    name: 'Pencil Torch',
    category: 'Novelties',
    price: 4.35,
    piece_count: '1 Piece',
    unit_price: 4.35,
    unit_name: 'piece',
    bundle_rate: 435.00,
    bundle_unit: '5 Boxes (100 Pcs)',
    unit_breakdown: '₹435.00 / 5 Boxes → ₹4.35 / piece',
    description: 'Slim pencil torch throwing vibrant colored flame and gold stars.',
    safety_instructions: 'Hold by bottom base pointing up.',
    safety_tags: ['Pencil Torch', 'Color Flame', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0502',
    code: '0502',
    name: 'Pencil Deluxe',
    category: 'Novelties',
    price: 8.82,
    piece_count: '1 Piece',
    unit_price: 8.82,
    unit_name: 'piece',
    bundle_rate: 882.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹882.00 / 10 Boxes → ₹8.82 / piece',
    description: 'Heavy deluxe pencil torch with high luminous star discharge.',
    safety_instructions: 'Keep away from hair and loose clothes.',
    safety_tags: ['Pencil Deluxe', 'Luminous Stars', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0509',
    code: '0509',
    name: 'Mint Candle',
    category: 'Novelties',
    price: 10.26,
    piece_count: '1 Piece',
    unit_price: 10.26,
    unit_name: 'piece',
    bundle_rate: 1026.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,026.00 / 10 Boxes → ₹10.26 / piece',
    description: 'Refreshing cool green flame candle torch emitting bright emerald sparks.',
    safety_instructions: 'Hold at arm length.',
    safety_tags: ['Mint Green', 'Cool Flame', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0504',
    code: '0504',
    name: 'Red Candle Torch',
    category: 'Novelties',
    price: 12.00,
    piece_count: '1 Piece',
    unit_price: 12.00,
    unit_name: 'piece',
    bundle_rate: 1200.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,200.00 / 10 Boxes → ₹12.00 / piece',
    description: 'Rich ruby red flame candle throwing high-intensity colored illumination.',
    safety_instructions: 'Hold vertically pointing away from body.',
    safety_tags: ['Ruby Red Flame', 'High Intensity', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0505',
    code: '0505',
    name: 'Rainbow Candle',
    category: 'Novelties',
    price: 30.00,
    piece_count: '1 Piece',
    unit_price: 30.00,
    unit_name: 'piece',
    bundle_rate: 150.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹150.00 / box (5 Pcs) → ₹30.00 / piece',
    description: 'Sequential rainbow color flame candle transitioning through 7 spectrum shades.',
    safety_instructions: 'Outdoor use recommended.',
    safety_tags: ['Rainbow Spectrum', '7 Shades', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0507',
    code: '0507',
    name: 'Twin Birds',
    category: 'Novelties',
    price: 56.00,
    piece_count: '1 Piece',
    unit_price: 56.00,
    unit_name: 'piece',
    bundle_rate: 112.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹112.00 / box (2 Pcs) → ₹56.00 / piece',
    description: 'Dual aerial novelty ascending in twin spirals with fluttering wing sounds and color discharge.',
    safety_instructions: 'Launch from clear ground. Step back 8m.',
    safety_tags: ['Twin Spirals', 'Fluttering Wings', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0508',
    code: '0508',
    name: 'Chenda Melam (Crackling)',
    category: 'Novelties',
    price: 74.00,
    piece_count: '1 Piece',
    unit_price: 74.00,
    unit_name: 'piece',
    bundle_rate: 148.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹148.00 / box (2 Pcs) → ₹74.00 / piece',
    description: 'Kerala traditional percussion inspired rhythmic crackling novelty with fast energetic beats.',
    safety_instructions: 'Place upright. Clear 6m.',
    safety_tags: ['Percussion Rhythm', 'Fast Beats', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 6. ATOM BOMBS (Page 3)
  // (Calculated per individual bomb)
  // =========================================================================
  {
    id: 'ayyan-0605',
    code: '0605',
    name: 'Hydrogen Bomb',
    category: 'Atom Bombs',
    price: 4.70,
    piece_count: '1 Piece',
    unit_price: 4.70,
    unit_name: 'piece',
    bundle_rate: 470.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹470.00 / 10 Boxes → ₹4.70 / piece',
    description: 'High decibel green foil wrapped salute bomb producing a crisp reverberating detonation report.',
    safety_instructions: 'Place on open ground. Light fuse and retreat 10 meters immediately.',
    safety_tags: ['High Decibel', 'Salute Bomb', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0610',
    code: '0610',
    name: 'Hydrogen Bomb Foils',
    category: 'Atom Bombs',
    price: 7.00,
    piece_count: '1 Piece',
    unit_price: 7.00,
    unit_name: 'piece',
    bundle_rate: 700.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹700.00 / 10 Boxes → ₹7.00 / piece',
    description: 'Heavy duty metallic foil sound bomb with extra sharp titanium percussion burst.',
    safety_instructions: 'Never light in enclosed spaces. Retreat 12m.',
    safety_tags: ['Metallic Foil', 'Titanium Burst', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0611',
    code: '0611',
    name: 'Cake Bomb Big Foils',
    category: 'Atom Bombs',
    price: 8.20,
    piece_count: '1 Piece',
    unit_price: 8.20,
    unit_name: 'piece',
    bundle_rate: 820.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹820.00 / 10 Boxes → ₹8.20 / piece',
    description: 'Giant sized foil wrapped salute block with maximum permissible decibel intensity.',
    safety_instructions: 'Adult use only. Clear 15m perimeter.',
    safety_tags: ['Max Decibel', 'Giant Foil Block', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 7. COMBINATION FIREWORKS & LOOSE CRACKERS (Page 4)
  // (Calculated per individual unit)
  // =========================================================================
  {
    id: 'ayyan-0851',
    code: '0851',
    name: 'Double Sound Small',
    category: 'Combination Crackers',
    price: 22.40,
    piece_count: '1 Packet',
    unit_price: 22.40,
    unit_name: 'packet',
    bundle_rate: 2240.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹2,240.00 / 100 Pkts → ₹22.40 / packet',
    description: 'Dual sequential sound cracker firing an initial report on the ground followed by aerial burst.',
    safety_instructions: 'Place upright. Step back 10m.',
    safety_tags: ['Double Sound', 'Ground + Aerial', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0852',
    code: '0852',
    name: 'Double Sound Big',
    category: 'Combination Crackers',
    price: 33.00,
    piece_count: '1 Packet',
    unit_price: 33.00,
    unit_name: 'packet',
    bundle_rate: 3300.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹3,300.00 / 100 Pkts → ₹33.00 / packet',
    description: 'Heavy caliber double salute with intense ground ignition and thunderous high sky break.',
    safety_instructions: 'Maintain 12m distance.',
    safety_tags: ['Heavy Caliber', 'Double Salute', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0853',
    code: '0853',
    name: 'Three Sound with Colour',
    category: 'Combination Crackers',
    price: 42.00,
    piece_count: '1 Packet',
    unit_price: 42.00,
    unit_name: 'packet',
    bundle_rate: 4200.00,
    bundle_unit: '100 Pkts',
    unit_breakdown: '₹4,200.00 / 100 Pkts → ₹42.00 / packet',
    description: 'Triple sound sequential cracker discharging vibrant emerald and ruby star balls between reports.',
    safety_instructions: 'Clear 15m perimeter.',
    safety_tags: ['3 Sound Burst', 'Color Star Balls', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0854',
    code: '0854',
    name: 'Flower Bomb Deluxe',
    category: 'Combination Crackers',
    price: 14.00,
    piece_count: '1 Piece',
    unit_price: 14.00,
    unit_name: 'piece',
    bundle_rate: 1400.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,400.00 / 10 Boxes → ₹14.00 / piece',
    description: 'Combines a rich floral fountain spray with a sudden surprise salute finish.',
    safety_instructions: 'Place upright on open ground. Retreat 8m.',
    safety_tags: ['Flower + Bomb', 'Surprise Salute', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0855',
    code: '0855',
    name: 'Tri Colour Balls',
    category: 'Combination Crackers',
    price: 30.00,
    piece_count: '1 Piece',
    unit_price: 30.00,
    unit_name: 'piece',
    bundle_rate: 60.00,
    bundle_unit: '1 Box (2 Pcs)',
    unit_breakdown: '₹60.00 / box (2 Pcs) → ₹30.00 / piece',
    description: 'Tri-color spherical fireworks emitting red, gold, and green glowing canopies.',
    safety_instructions: 'Light fuse and retreat 6m.',
    safety_tags: ['Tri-Color Spheres', 'Glowing Canopy', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-8560',
    code: '8560',
    name: 'Tito Special (3 Colours)',
    category: 'Combination Crackers',
    price: 14.33,
    piece_count: '1 Piece',
    unit_price: 14.33,
    unit_name: 'piece',
    bundle_rate: 43.00,
    bundle_unit: '1 Box (3 Pcs)',
    unit_breakdown: '₹43.00 / box (3 Pcs) → ₹14.33 / piece',
    description: 'Special 3-color novelty combination delivering vivid aerial color pearls.',
    safety_instructions: 'Clear 5m.',
    safety_tags: ['3 Colours Tito', 'Color Pearls', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-8561',
    code: '8561',
    name: 'Ulta Pulta',
    category: 'Combination Crackers',
    price: 16.20,
    piece_count: '1 Piece',
    unit_price: 16.20,
    unit_name: 'piece',
    bundle_rate: 81.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹81.00 / box (5 Pcs) → ₹16.20 / piece',
    description: 'Playful flip-spin novelty cracker that jumps and rotates with multi-color spark flashes.',
    safety_instructions: 'Ensure level open ground.',
    safety_tags: ['Flip Spin', 'Playful Jump', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0901',
    code: '0901',
    name: 'Loose Crackers Red Bijili',
    category: 'Maroons',
    price: 40.80,
    piece_count: '1 Bag of 100',
    unit_price: 40.80,
    unit_name: 'bag of 100',
    bundle_rate: 408.00,
    bundle_unit: '10 Bags (1,000 Pcs)',
    unit_breakdown: '₹408.00 / 10 Bags → ₹40.80 / bag of 100',
    description: 'Authentic Sivakasi red bijili sound crackers packed in bags of 100 with rapid firecracker burst.',
    safety_instructions: 'Scatter on open ground or light string from fuse. Step back 8m.',
    safety_tags: ['Red Bijili', '100 Pcs Bag', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-0902',
    code: '0902',
    name: 'Loose Crackers Stripped Bijili',
    category: 'Maroons',
    price: 42.00,
    piece_count: '1 Bag of 100',
    unit_price: 42.00,
    unit_name: 'bag of 100',
    bundle_rate: 420.00,
    bundle_unit: '10 Bags (1,000 Pcs)',
    unit_breakdown: '₹420.00 / 10 Bags → ₹42.00 / bag of 100',
    description: 'Traditional stripped pattern bijili crackers with snappy continuous report.',
    safety_instructions: 'Light safely with agarbatti. Retreat 8m.',
    safety_tags: ['Stripped Bijili', 'Snappy Report', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 8. ROCKETS (Page 4)
  // (Calculated per individual rocket stick)
  // =========================================================================
  {
    id: 'ayyan-1202',
    code: '1202',
    name: 'Colour Rocket',
    category: 'Sky Rockets',
    price: 6.50,
    piece_count: '1 Rocket',
    unit_price: 6.50,
    unit_name: 'piece',
    bundle_rate: 650.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹650.00 / 10 Boxes → ₹6.50 / piece',
    description: 'High-altitude vertical ascent with starry color parachute and emerald star burst.',
    safety_instructions: 'Place stick upright in a stable launch bottle or tube on open ground. Never hold in hand.',
    safety_tags: ['Vertical Ascent', 'Color Burst', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1203',
    code: '1203',
    name: 'Rocket Bomb',
    category: 'Sky Rockets',
    price: 7.94,
    piece_count: '1 Rocket',
    unit_price: 7.94,
    unit_name: 'piece',
    bundle_rate: 794.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹794.00 / 10 Boxes → ₹7.94 / piece',
    description: 'Fast whistling ascent ending in heavy aerial salute report high in the night sky.',
    safety_instructions: 'Launch vertically only. Check for overhead wires.',
    safety_tags: ['Fast Ascent', 'Salute Report', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1204',
    code: '1204',
    name: 'Flower Missile Rocket',
    category: 'Sky Rockets',
    price: 7.50,
    piece_count: '1 Rocket',
    unit_price: 7.50,
    unit_name: 'piece',
    bundle_rate: 750.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹750.00 / 10 Boxes → ₹7.50 / piece',
    description: 'Rocket with sparkling floral spray trailing the sky followed by floral star bloom.',
    safety_instructions: 'Use stable launch guide tube.',
    safety_tags: ['Floral Missile', 'Star Bloom', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1205',
    code: '1205',
    name: 'Sound Missile Rocket',
    category: 'Sky Rockets',
    price: 9.30,
    piece_count: '1 Rocket',
    unit_price: 9.30,
    unit_name: 'piece',
    bundle_rate: 930.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹930.00 / 10 Boxes → ₹9.30 / piece',
    description: 'Whistling high report aerial missile roaring to 200 feet before detonating with a loud bang.',
    safety_instructions: 'Clear 15m perimeter.',
    safety_tags: ['200ft Altitude', 'High Decibel Bang', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1206',
    code: '1206',
    name: 'Multi Colour Rocket',
    category: 'Sky Rockets',
    price: 10.12,
    piece_count: '1 Rocket',
    unit_price: 10.12,
    unit_name: 'piece',
    bundle_rate: 1012.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,012.00 / 10 Boxes → ₹10.12 / piece',
    description: 'High altitude multi-color starburst rocket releasing ruby, sapphire, and gold pearls.',
    safety_instructions: 'Launch from clear open grounds.',
    safety_tags: ['Multi Colour Pearls', 'High Altitude', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1207',
    code: '1207',
    name: 'Double Sound Rocket',
    category: 'Sky Rockets',
    price: 11.45,
    piece_count: '1 Rocket',
    unit_price: 11.45,
    unit_name: 'piece',
    bundle_rate: 1145.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,145.00 / 10 Boxes → ₹11.45 / piece',
    description: 'Twin stage rocket firing two thunderous aerial reports at high elevation.',
    safety_instructions: 'Ensure vertical tube guidance.',
    safety_tags: ['Double Aerial Report', 'Twin Stage', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1208',
    code: '1208',
    name: 'Deluxe Rocket Colour',
    category: 'Sky Rockets',
    price: 10.40,
    piece_count: '1 Rocket',
    unit_price: 10.40,
    unit_name: 'piece',
    bundle_rate: 1040.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,040.00 / 10 Boxes → ₹10.40 / piece',
    description: 'Deluxe high power rocket creating a dense spherical color peony in the sky.',
    safety_instructions: 'Step back 15m.',
    safety_tags: ['Spherical Peony', 'Deluxe Color', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1209',
    code: '1209',
    name: 'Classic Rocket Sound',
    category: 'Sky Rockets',
    price: 12.20,
    piece_count: '1 Rocket',
    unit_price: 12.20,
    unit_name: 'piece',
    bundle_rate: 1220.00,
    bundle_unit: '10 Boxes (100 Pcs)',
    unit_breakdown: '₹1,220.00 / 10 Boxes → ₹12.20 / piece',
    description: 'Maximum power sound rocket with deep titanium bass explosion.',
    safety_instructions: 'Wide open field only. Keep 20m distance.',
    safety_tags: ['Titanium Bass', 'Max Sound Power', 'PESO Certified'],
    sound_level: 'High Spectacle',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1210',
    code: '1210',
    name: 'Parachute Rocket',
    category: 'Sky Rockets',
    price: 53.75,
    piece_count: '1 Rocket',
    unit_price: 53.75,
    unit_name: 'piece',
    bundle_rate: 215.00,
    bundle_unit: '1 Box (4 Pcs)',
    unit_breakdown: '₹215.00 / box (4 Pcs) → ₹53.75 / piece',
    description: 'Ascends 100+ meters and slowly descends with a glowing luminous color flare on an authentic parachute.',
    safety_instructions: 'Use in wide open fields away from power lines.',
    safety_tags: ['Parachute Descent', '100m Flare', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1213',
    code: '1213',
    name: 'Air Whistle Rocket',
    category: 'Sky Rockets',
    price: 14.50,
    piece_count: '1 Rocket',
    unit_price: 14.50,
    unit_name: 'piece',
    bundle_rate: 145.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹145.00 / box (10 Pcs) → ₹14.50 / piece',
    description: 'Auditory whistling sky rocket ascending with musical siren effect.',
    safety_instructions: 'Launch vertically from open ground with launch bottle.',
    safety_tags: ['Musical Siren', 'Sky Whistle', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1214',
    code: '1214',
    name: 'Super Whistle Rocket',
    category: 'Sky Rockets',
    price: 23.00,
    piece_count: '1 Rocket',
    unit_price: 23.00,
    unit_name: 'piece',
    bundle_rate: 230.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹230.00 / box (10 Pcs) → ₹23.00 / piece',
    description: 'Heavy caliber whistling sky rocket with high-pitched shrieking ascent and star burst.',
    safety_instructions: 'Ensure unobstructed upward trajectory.',
    safety_tags: ['Super Whistle', 'High Pitched', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },

  // =========================================================================
  // 9. FANCY NOVELTIES (Page 4)
  // (Calculated per individual piece)
  // =========================================================================
  {
    id: 'ayyan-1300',
    code: '1300',
    name: 'Pop Pop (Crackling)',
    category: 'Novelties',
    price: 2.70,
    piece_count: '1 Piece',
    unit_price: 2.70,
    unit_name: 'piece',
    bundle_rate: 27.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹27.00 / box (10 Pcs) → ₹2.70 / piece',
    description: 'Snappy friction pop-pops bursting on hard surfaces with harmless celebratory crackles.',
    safety_instructions: 'Throw firmly against hard pavement. Safe for children.',
    safety_tags: ['Pop Pop', 'Friction Crackle', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1303',
    code: '1303',
    name: 'Crackling Pop Corn',
    category: 'Novelties',
    price: 4.00,
    piece_count: '1 Piece',
    unit_price: 4.00,
    unit_name: 'piece',
    bundle_rate: 40.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹40.00 / box (10 Pcs) → ₹4.00 / piece',
    description: 'Playful jumping crackling novelty jumping like sizzling pop corn on the ground.',
    safety_instructions: 'Place on open ground. Light and step back 3m.',
    safety_tags: ['Jumping Popcorn', 'Crackling Spark', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1349',
    code: '1349',
    name: 'Seven Shot Gold',
    category: 'Novelties',
    price: 20.00,
    piece_count: '1 Piece',
    unit_price: 20.00,
    unit_name: 'piece',
    bundle_rate: 100.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹100.00 / box (5 Pcs) → ₹20.00 / piece',
    description: '7 sequential high-velocity golden pearl shots firing into the night sky.',
    safety_instructions: 'Insert launch guide into stable ground. Retreat 6m.',
    safety_tags: ['7 Shot Gold', 'Golden Pearls', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1308',
    code: '1308',
    name: 'Dancing Butterfly',
    category: 'Novelties',
    price: 20.00,
    piece_count: '1 Piece',
    unit_price: 20.00,
    unit_name: 'piece',
    bundle_rate: 100.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹100.00 / box (5 Pcs) → ₹20.00 / piece',
    description: 'Whirling winged novelty that takes flight spinning with emerald and ruby sparkling wings.',
    safety_instructions: 'Place flat on open ground. Clear 5m.',
    safety_tags: ['Winged Flight', 'Dancing Butterfly', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-8570',
    code: '8570',
    name: 'Super Drone',
    category: 'Novelties',
    price: 7.20,
    piece_count: '1 Piece',
    unit_price: 7.20,
    unit_name: 'piece',
    bundle_rate: 72.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹72.00 / box (10 Pcs) → ₹7.20 / piece',
    description: 'Mini helicopter drone lifting 30 feet into the air with spinning rotor lights.',
    safety_instructions: 'Ensure clear sky above.',
    safety_tags: ['Helicopter Drone', 'Rotor Lights', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1309',
    code: '1309',
    name: 'Funny Bunny',
    category: 'Novelties',
    price: 19.20,
    piece_count: '1 Piece',
    unit_price: 19.20,
    unit_name: 'piece',
    bundle_rate: 96.00,
    bundle_unit: '1 Box (5 Pcs)',
    unit_breakdown: '₹96.00 / box (5 Pcs) → ₹19.20 / piece',
    description: 'Iconic Bunny Brand novelty jumping and spinning with colorful sparks and cheerful crackles.',
    safety_instructions: 'Flat ground placement. Step back 4m.',
    safety_tags: ['Bunny Brand', 'Jumping Novelty', 'PESO Certified'],
    sound_level: 'Low / Silent',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  },
  {
    id: 'ayyan-1310',
    code: '1310',
    name: 'Magic Mystery',
    category: 'Novelties',
    price: 11.00,
    piece_count: '1 Piece',
    unit_price: 11.00,
    unit_name: 'piece',
    bundle_rate: 110.00,
    bundle_unit: '1 Box (10 Pcs)',
    unit_breakdown: '₹110.00 / box (10 Pcs) → ₹11.00 / piece',
    description: 'Multi-stage mystery box novelty that transforms across 3 surprising audio-visual effects.',
    safety_instructions: 'Place on open ground. Retreat 5m.',
    safety_tags: ['Magic Mystery', '3-Stage Effect', 'PESO Certified'],
    sound_level: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    is_active: true,
  }
];

// Add the other product sections: Aerial Novelties, Shells, Cakes, Mega Displays, Matches
// and write out initialData.ts
console.log(`Loaded ${PRODUCTS.length} foundational items from Pages 1-4.`);
